{"name": "Неуспешная авторизация с неверным логином и паролем", "status": "passed", "start": 1733268645081, "stop": 1733268645320, "uuid": "120fb2e7-f70a-4dcd-8c09-a44d95995401", "historyId": "a2a4201d2f86c863ca53c2a94e65190c", "testCaseId": "a2a4201d2f86c863ca53c2a94e65190c", "fullName": "tests.test_login_user.TestUserLogin#test_failed_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "NB-PF2VZBPJ"}, {"name": "thread", "value": "10420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}